--- #This for installation of httpd server
- hosts: client2.abc.com
  user: root
  become: yes
  gather_facts: yes
  tasks:
  - name: install httpd
    yum: name=httpd state=installed
  - name: copy index.html
    copy: src=index.html dest=/var/www/html/index.html
  - name: start httpd service
    service: name=httpd state=restarted
